------------------------------ DATES --------------------------------------
SELECT GETDATE()  -- shows the current date

SELECT GETDATE() - 2

-- DATEPART
SELECT DATEPART(yyyy, GETDATE()) AS YEARNUMBER

SELECT DATEPART(MM, GETDATE()) AS MONTH

SELECT DATEPART(DD, GETDATE()) AS DAY

-- DATEADD
SELECT DATEADD(day, 4, GETDATE())
SELECT DATEADD(day, 4, '7/4/2016')

SELECT DATEADD(month, 4, GETDATE())

SELECT DATEADD(year, 4, GETDATE())

--
SELECT TOP 10 * FROM Production.WorkOrder

-- SHOW DIFFERENCE IN DAYS FOR START DATE AND END DATES
SELECT TOP 10 WORKORDERID, PRODUCTID, STARTDATE, ENDDATE, DATEDIFF(day, STARTDATE, ENDDATE) AS DATE_DIFF
FROM PRODUCTION.WorkOrder

-- GET FIRST DAY OF THIS MONTH
SELECT DATEADD(dd, - (DATEPART(day, GETDATE()) - 1), GETDATE())