------------------------------ TSQL DATE FUNCTIONS SECTION --------------------------------------
---------- DATES -------------
SELECT GETDATE()  -- shows the current date

SELECT GETDATE() - 2

-- DATEPART
SELECT DATEPART(yyyy, GETDATE()) AS YEARNUMBER

SELECT DATEPART(MM, GETDATE()) AS MONTH

SELECT DATEPART(DD, GETDATE()) AS DAY

-- DATEADD
SELECT DATEADD(day, 4, GETDATE())
SELECT DATEADD(day, 4, '7/4/2016')

SELECT DATEADD(month, 4, GETDATE())

SELECT DATEADD(year, 4, GETDATE())

--
SELECT TOP 10 * FROM Production.WorkOrder

-- SHOW DIFFERENCE IN DAYS FOR START DATE AND END DATES
SELECT TOP 10 WORKORDERID, PRODUCTID, STARTDATE, ENDDATE, DATEDIFF(day, STARTDATE, ENDDATE) AS DATE_DIFF
FROM PRODUCTION.WorkOrder

-- GET FIRST DAY OF THIS MONTH
SELECT DATEADD(dd, - (DATEPART(day, GETDATE()) - 1), GETDATE())


------------------------------ TSQL AGGREGATION AND STRING FUNCTIONS SECTION --------------------------------------
-- WILL USE MYSALARIES TABLE
-- AGGREGATE FUNCTIONS
SELECT * FROM MYSALARIES

SELECT AVG(SALARY) FROM MYSALARIES

SELECT COUNT(SALARY) FROM MYSALARIES
SELECT COUNT(*) FROM MYSALARIES

SELECT * FROM MYSALARIES

SELECT SUM(SALARY) FROM MYSALARIES

SELECT MIN(SALARY) FROM MYSALARIES

SELECT MAX(SALARY) FROM MYSALARIES

-- MYORDER TABLE
-- STRING FUNCTIONS
SELECT * FROM MYORDER

-- CONCAT
PRINT CONCAT('String1', 'String 2')

SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNUMBER, ' - ', ORDERNAME) AS CONCATENATEDTEXT
FROM MYORDER

SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNUMBER, ' - ', RAND()) AS CONCATENATEDTEXT
FROM MYORDER

-- LEFT
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 5) FROM MYORDER

-- RIGHT
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 5) FROM MYORDER

-- SUBSTRING
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 2, 5) FROM MYORDER

-- LOWERCASE
SELECT ORDERNUMBER, ORDERNAME, LOWER(ORDERNAME) FROM MYORDER

-- UPPER
SELECT ORDERNUMBER, ORDERNAME, UPPER(ORDERNAME) FROM MYORDER

-- LENGTH
SELECT ORDERNUMBER, ORDERNAME, LEN(ORDERNAME) FROM MYORDER

-- DISPLAY FIRST CHARACTER IN UPPERCASE AND THE REST IN LOWERCASE
SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(SUBSTRING(ORDERNAME, 1, 1)), LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME)))) 
FROM MYORDER
-- CAN ALSO BE WRITTEN LIKE THIS
SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME, 1)), LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME))))
FROM MYORDER

--TRIM
-- EXAMPLE TEXT
SELECT '    -MYTEXT-     '
SELECT LEN('    -MYTEXT-   ')

-- LTRIM
SELECT LTRIM('    -MYTEXT-    ')

--RTRIM
SELECT RTRIM('    -MYTEXT-    ')

-- REMOVE SPACES FROM BOTH SIDES
SELECT LTRIM(RTRIM('    -MYTEXT-    '));